### ISSUE TITLE
MultiBoardAssembly commands error

### ISSUE THREAD

**Issue by sawcheg** [Altium-Designer-addons/scripts-libraries#113]
Hi, 
I'm developing now a plugin for exporting Altium Designer files to PDF and I've encountered a problem with the *.MbsDoc format.
I found the necessary command, it is in the MultiBoardAssembly module.

But calling any command in this module ends with a "catastrophic failure" error. 
For example, you can run this script in Altuim
`Begin`
    `// create and open file`
    `ResetParameters;`
    `AddStringParameter ('ObjectKind'  ,'NewAnything');`
    `AddStringParameter ('Kind'  ,'SdDoc');`
    `RunProcess('WorkspaceManager:OpenObject');`
    `// export to pdf`
    `ResetParameters;`
    `AddStringParameter ('Action'  ,'ExportToPDF3D');`
    `RunProcess('MultiBoardAssembly:ExportPart');`
`End;`

Can you add a script for working with the module MultiBoardAssembly to the examples? Or tell me please what could be wrong in this script.

Thanks

**Comment by justinmassiot** [comment]
Hello @sawcheg ,
Unfortunately, if there isn't any existing script corresponding to what you look for in our community repository, it means that nobody has one (or nobody can/wants to share it).
Good luck.
