### ISSUE TITLE
Trouble with Altium Pinout Script

### ISSUE THREAD

**Issue by ShmuelDavis** [Altium-Designer-addons/scripts-libraries#15]
I am trying to run the import and export pin swap info for specific vendor script copied from the following 

https://github.com/Altium-Designer-addons/scripts-libraries/blob/master/VendorTools/VendorTools.pas

However I am getting an "undeclared indentifier: ComboBoxDesignator" error on the following line :- 

ComboBoxDesignator.Items.Add(FlatHierarchy.DM_Components(ComponentNum).DM_PhysicalDesignator); 
Please can someone help ?

**Comment by lunarplasma** [comment]
That script has a gui form, so the entire script project needs to be run, and not just the function in the `.pas` file.
