### ISSUE TITLE
Issue in PlanarTx script

### ISSUE THREAD

**Issue by ashokshamanna** [Altium-Designer-addons/scripts-libraries#64]
![PLtx_error](https://user-images.githubusercontent.com/86527227/123518442-957e9600-d6c3-11eb-9457-7098e1950509.jpg)

getting error while running script in Altium 21

**Comment by justinmassiot** [comment]
I have personaly never experienced such a problem, neither in AD 21.9.2 (build 33) nor in AD 22.8.2 (build 66).
Then I consider this issue can be closed.

**Comment by antifar** [comment]
邮件已收到，祝好。^_^
