### ISSUE TITLE
CopyDesignatorsToMechLayerPair does not work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Altium-Designer-addons/scripts-libraries#7]
```
What steps will reproduce the problem?
1. AD15.0.8
2. Run Script
3. Fails on line 73 complaining about LayerObject_V7

To get the script to work I modified it to iterate from 1 to 16 (Fails on layer 
17 for me) and changed the line to contain 
Board.LayerStack.LayerObject[ILayer.MechanicalLayer(i)]
as well as on line 200.

This is a total hack though. The 1 to 16 thing maybe because I am/am not using 
layer pairs or something.

What version of the product are you using? On what operating system?
AD15.0.8 on Windows 7 x64

Please provide any additional information below.


```

Original issue reported on code.google.com by `alblay.e...@gmail.com` on 15 Jan 2015 at 11:48

Attachments:
- [CopyDesignatorsToMechLayerPair.pas](https://storage.googleapis.com/google-code-attachments/altium-designer-addons/issue-7/comment-0/CopyDesignatorsToMechLayerPair.pas)

**Comment by justinmassiot** [comment]
I don't think that the proposed hack is a good way to solve the issue. As the issue is old and the code has never be integrated in the master branch I prefer to close the ticket. Please re-open it if the bug remains.

**Comment by Manu3l0us** [comment]
I don't know if this is the same issue I experienced but I got the script running in AD18.1.9 by replacing `Board.LayerStack.LayerObject_V7` with `Board.LayerStack_V7.LayerObject_V7`. Don't know if this works in earlier versions, I don't have access.
